[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/githubql"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
